server:
  port: 17593
# zookeeper配置
route:
  zk-root: /route
  zk-address: localhost:2181
  zk-connect-timeout: 15000
  route-way: cn.v2ss.common.route.algorithm.hash.ConsistentHashHandle
  consistent-hash-way: cn.v2ss.common.route.algorithm.hash.TreeMapConsistentHash
# zookeeper连接框架配置
curator:
  retry-count: 5
  elapsed-time-ms: 5000
  # 集群的话用“，”隔开
  connect-string: 127.0.0.1:2181
  session-timeout-ms: 6000
  connection-timeout-ms: 5000